import "./globals.css";
import Head from "next/head";
import { Archivo, Open_Sans } from "next/font/google";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import BackgroundOrbs from "../components/BackgroundOrbs";

const archivo = Archivo({
  subsets: ["latin"],
  display: "swap",
  weight: "500",
  variable: "--font-archivo",
});

const opensans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
  weight: "300",
  variable: "--font-opensans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <body
        className={`${archivo.variable} ${opensans.variable} bg-brand-primary text-brand-textBody`}
      >
        <Navbar />
        {children}
        <Footer />
        <BackgroundOrbs />
      </body>
    </html>
  );
}
