import "./globals.css";
import { Archivo, Open_Sans } from "next/font/google";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import BackgroundOrbs from "../components/BackgroundOrbs";

const archivo = Archivo({
  subsets: ["latin"],
  display: "swap",
  weight: "500",
  variable: "--font-archivo",
});

const opensans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
  weight: "300",
  variable: "--font-opensans",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${archivo.variable} ${opensans.variable} bg-brand-primary text-brand-textBody h-screen items-center justify-center`}
      >
        <Navbar />
        <div className="sticky top-0 mx-auto max-w-xs md:max-w-xl lg:max-w-3xl xl:max-w-5xl z-[-10]">
          <BackgroundOrbs />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
