/* eslint-disable import/no-anonymous-default-export */
export default [
  {
    id: "1",
    name: "Zach Mutch",
    title: "Front-end Developer",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    rateLow: "300",
    rateHigh: "1000",
    portfolioUrl: "https://www.thatdevguy.app/",
    githubUrl: "https://github.com/that-devguy",
    linkedinUrl: "https://linkedin.com/in/zachmutch/",
    available: true,
  },
  {
    id: "2",
    name: "Christian Smith",
    title: "Front-end Developer",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    rateLow: "300",
    rateHigh: "1000",
    portfolioUrl: "https://www.thatdevguy.app/",
    githubUrl: "https://github.com/that-devguy",
    linkedinUrl: "https://linkedin.com/in/zachmutch/",
    available: true,
  },
  {
    id: "3",
    name: "Nathan Moon",
    title: "Front-end Developer",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    rateLow: "300",
    rateHigh: "1000",
    portfolioUrl: "https://www.thatdevguy.app/",
    githubUrl: "https://github.com/that-devguy",
    linkedinUrl: "https://linkedin.com/in/zachmutch/",
    available: true,
  },
  {
    id: "4",
    name: "Chelsea Luevano",
    title: "Front-end Developer",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    rateLow: "300",
    rateHigh: "1000",
    portfolioUrl: "https://www.thatdevguy.app/",
    githubUrl: "https://github.com/that-devguy",
    linkedinUrl: "https://linkedin.com/in/zachmutch/",
    available: true,
  },
  {
    id: "5",
    name: "Xander Wyckoff",
    title: "Front-end Developer",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    rateLow: "300",
    rateHigh: "1000",
    portfolioUrl: "https://www.thatdevguy.app/",
    githubUrl: "https://github.com/that-devguy",
    linkedinUrl: "https://linkedin.com/in/zachmutch/",
    available: true,
  },
  {
    id: "6",
    name: "Ryan Spath",
    title: "Front-end Developer",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    rateLow: "300",
    rateHigh: "1000",
    portfolioUrl: "https://www.thatdevguy.app/",
    githubUrl: "https://github.com/that-devguy",
    linkedinUrl: "https://linkedin.com/in/zachmutch/",
    available: true,
  },
];
