/* eslint-disable import/no-anonymous-default-export */
export default [
  {
    id: "1",
    firstName: "Zach",
    lastName: "Mutch",
    title: "Front-end Developer",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    rateLow: "300",
    rateHigh: "1000",
    portfolioUrl: "https://www.thatdevguy.app/",
    githubUrl: "https://github.com/that-devguy",
    linkedinUrl: "https://linkedin.com/in/zachmutch/",
    available: true,
  },
  {
    id: "2",
    firstName: "Christian",
    lastName: "Smith",
    title: "Front-end Developer",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    rateLow: "300",
    rateHigh: "1000",
    portfolioUrl: "https://www.thatdevguy.app/",
    githubUrl: "https://github.com/that-devguy",
    linkedinUrl: "https://linkedin.com/in/zachmutch/",
    available: true,
  },
  {
    id: "3",
    firstName: "Nathan",
    lastName: "Moon",
    title: "Front-end Developer",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    rateLow: "300",
    rateHigh: "1000",
    portfolioUrl: "https://www.thatdevguy.app/",
    githubUrl: "https://github.com/that-devguy",
    linkedinUrl: "https://linkedin.com/in/zachmutch/",
    available: true,
  },
  {
    id: "4",
    firstName: "Chelsea",
    lastName: "Luevano",
    title: "Front-end Developer",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    rateLow: "300",
    rateHigh: "1000",
    portfolioUrl: "https://www.thatdevguy.app/",
    githubUrl: "https://github.com/that-devguy",
    linkedinUrl: "https://linkedin.com/in/zachmutch/",
    available: true,
  },
  {
    id: "5",
    firstName: "Xander",
    lastName: "Wyckoff",
    title: "Front-end Developer",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    rateLow: "300",
    rateHigh: "1000",
    portfolioUrl: "https://www.thatdevguy.app/",
    githubUrl: "https://github.com/that-devguy",
    linkedinUrl: "https://linkedin.com/in/zachmutch/",
    available: true,
  },
  {
    id: "6",
    firstName: "Ryan",
    lastName: "Spath",
    title: "Front-end Developer",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.",
    rateLow: "300",
    rateHigh: "1000",
    portfolioUrl: "https://www.thatdevguy.app/",
    githubUrl: "https://github.com/that-devguy",
    linkedinUrl: "https://linkedin.com/in/zachmutch/",
    available: true,
  },
];
